version: '3.7'

services:
  # Redis service
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379" # Mapeamento da porta do host para a porta do contêiner

  rabbitmq:
    image: rabbitmq:3.12-management #management para poder abrir ele na url ele abre tipo o workbench para podermos configurar filas etc
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

volumes:
  data: